
-- Wstawianie tajemnic różańcowych
INSERT INTO public.mysteries (id, part, name, meditation) VALUES
-- RADOSNE
(1, 'Radosna', 'Zwiastowanie', '"Oto ja Służebnica Pańska, niech mi się stanie według Twego Słowa" (Łk 1,38). Tak odpowiedziała Maryja na propozycję przedstawioną Jej przez Anioła, by - przez włączenie się w zbawcze plany Boże - została Matką Mesjasza i Zbawiciela całej ludzkości. Wspieraj nas, Maryjo, abyśmy umieli podejmować zawsze Boże wezwania i świadomie współpracować w dziele zbawienia świata.'),
(2, 'Radosna', 'Nawiedzenie św. Elżbiety', '"A skąd mi to, że Matka mojego Pana przychodzi do mnie?" (Łk 1,44). Te słowa wypowiedziała Elżbieta na widok Maryi wstępującej w jej dom i przynoszącej pomoc oraz samego Chrystusa i Jego błogosławieństwo. Maryjo, naucz nas nieść ludziom prawdziwą pomoc, jakiej w danej chwili potrzebują, oraz Boży pokój.'),
(3, 'Radosna', 'Narodzenie Chrystusa', '"Dziś narodził się wam Zbawiciel, którym jest Mesjasz Pan" (Łk 2,11). Tymi słowami obwieszczona została światu radosna nowina: Bóg stał się człowiekiem i narodził się w ludzkiej postaci po to, aby nas zbawić, aby stworzyć każdemu człowiekowi możliwość sięgania aż do Bożej rzeczywistości. Maryjo, rodząca światu Zbawiciela, naucz nas nieustannie rozpoznawać Boga i przyjmować Go zawsze, gdy do nas przychodzi.'),
(4, 'Radosna', 'Ofiarowanie Pana Jezusa', '"Oto ten przeznaczony jest na znak, któremu sprzeciwiać się będą" (Łk 2,34). Te prorocze słowa o Jezusie wypowiedział Symeon podczas ofiarowania w świątyni jerozolimskiej. Życie potwierdzi później ich całkowitą prawdziwość. Jedni będą wołać: "Witaj Królu", a inni będą krzyczeć: "Na Krzyż z nim". Maryjo, naucz nas rozpoznawać Chrystusa, który na zawsze pozostaje dla nas światłem rozjaśniającym mroki naszego pogańskiego myślenia i pogańskiego rozumienia życia.'),
(5, 'Radosna', 'Odnalezienie Jezusa w Świątyni', '"Dopiero po trzech dniach odnaleźli Go w świątyni" (Łk 2,46). Maryja i Józef wracali do Nazaretu z pielgrzymki do Świątyni Jerozolimskiej. Szli w przekonaniu, że Jezus jest także w grupie pielgrzymów. Dopiero po pewnym czasie spostrzegli, że Jezusa wśród powracających do Nazaretu pielgrzymów nie ma. Podjęli natychmiast poszukiwania i odnaleźli Go tam, gdzie po raz ostatni Go widzieli i z Nim byli: w Świątyni. Tam Jezus słuchał uczonych w Piśmie i zadawał im pytania. Maryjo, pomagaj nam zawsze, gdy zagubimy w życiu Chrystusa, poszukując Go skutecznie, aż do ponownego z Nim spotkania i zabrania Go znowu w naszą codzienność.'),

-- ŚWIATŁA
(6, 'Światła', 'Chrzest Jezusa w Jordanie', '"A gdy Jezus został ochrzczony... głos z nieba mówił: Ten jest mój Syn umiłowany, w którym mam upodobanie" (Mt 3,16). Janowi Chrzcicielowi przypadło zadanie bezpośredniego wskazania światu osoby Zbawiciela. Doszło więc do szczególnego spotkania Jezusa i Jana w miejscu, gdzie Jan chrzcił i przez chrzest pokuty przygotowywał naród wybrany na spotkanie z Mesjaszem. Przyjmując chrzest Janowy wszedł Jezus jeszcze pełniej w nasz ludzki świat znaczony grzechem, aby go z grzechu wyzwolić.'),
(7, 'Światła', 'Objawienie Jezusa na weselu w Kanie', '"Odbywało się wesele w Kanie Galilejskiej i była tam Matka Jezusa. Zaproszono na to wesele także Jezusa i Jego uczniów" (J 2,2). Podczas uroczystości weselnych, w pewnym momencie spostrzegła Maryja zakłopotanie gospodarzy, bo zabrakło wina. Zwraca się więc Maryja do Syna ze słowami "Wina nie mają", a do pozostałych mówi: "Zróbcie wszystko, cokolwiek wam powie". Tu w Kanie Galilejskiej po raz pierwszy tak widocznie i czytelnie objawił Chrystus swoją Boską Moc przemieniając wodę w wino. Uczynił to na prośbę i przez wstawiennictwo swojej Matki.'),
(8, 'Światła', 'Nauczanie Pana Jezusa', '"Jezus przyszedł do Galilei i głosił tam Ewangelię Bożą. Mówił: Czas się wypełnił i bliskie jest Królestwo Boże. Nawracajcie się i wierzcie w Ewangelię" (Mk 1,14). Wypełnił się czas obietnic dotyczących przyjścia Mesjasza. Nadszedł już czas realizacji zbawienia poprzez przyjęcie ogłoszonej prawdy. Z daru zbawienia skorzystać mogą ci, którzy uwierzą w Ewangelię, nawrócą się i podejmą życie znaczone nauką i przykładem Zbawiciela, Jezusa Chrystusa.'),
(9, 'Światła', 'Przemienienie Pańskie', '"Jezus wziął ze sobą Piotra, Jana i Jakuba i wszedł na górę... Gdy się modlił, wygląd Jego twarzy odmienił się, a Jego odzienie stało się lśniąco białe... Z obłoku odezwał się głos: to jest Syn mój umiłowany, Jego słuchajcie" (Łk 9,28). Zbliżała się męka i śmierć Chrystusa, chwila wielkiej próby wiary dla apostołów i uczniów Chrystusa. Jezus wziął niektórych na górę, by tam ukazać im inny jeszcze niż ludzki wymiar swego istnienia. Apostołowie dostrzegli w przemienionym na ich oczach Chrystusie Boga i dowiedzieli się od samego Ojca, że Jezus jest Synem Bożym, którego należy słuchać.'),
(10, 'Światła', 'Ustanowienie Eucharystii', '"To jest Ciało moje, które za was będzie wydane" (Łk 22,19). Wypowiadając te słowa w Wieczerniku Chrystus ustanowił sakrament Eucharystii, a nam polecił sprawować go na Jego pamiątkę. W taki to też sposób zrealizował Chrystus swoją obietnicę, że nie pozostawi nas samych. Pozostał z nami w eucharystycznych postaciach, byśmy się Nim karmili i zdobywali moc potrzebną nam podczas naszego pielgrzymowania i byśmy w drodze nie ustali.'),

-- BOLESNE
(11, 'Bolesna', 'Modlitwa Chrystusa w Ogrójcu', '"Ojcze mój, jeśli to możliwe, niech ominie mnie ten kielich" (Mt 26,39). Tak modlił się Chrystus w Ogrójcu na krótko przed swoją męką i śmiercią. Przywoływał też apostołów i wszystkich nas, abyśmy z Nim czuwali, bo jest to jedyne zabezpieczenie przed upadkiem w godzinie pokusy i próby. Mój Mistrzu, naucz i mnie wraz z Tobą przyjmować wolę Ojca. Tak bowiem dokonuje się zbawienie świata i moje własne.'),
(12, 'Bolesna', 'Biczowanie Chrystusa', '"Piłat kazał Jezusa ubiczować" (J 19,1). Co chciał osiągnąć Piłat skazując Jezusa na dodatkowe cierpienia, jakim było biczowanie? Być może spodziewał się, że ocali Jezusa od śmierci, że widok ubiczowanego położy kres dalszym żądaniom tłumu, który domagał się Jezusowej śmierci i to śmierci krzyżowej. Tak jednak się nie stało. Przepraszam Cię, Panie Jezu, za to, że zgadzam się niekiedy na zło i cierpienie bliźnich i tłumaczę sobie, że w ten sposób mogę osiągnąć większe dobro i coś w ogóle ocalić.'),
(13, 'Bolesna', 'Ukoronowanie cierniem Chrystusa', '"Ja na to przyszedłem na świat, aby dać świadectwo prawdzie" (J 18,17). Tak określił swą misję Chrystus zapytany przez Piłata, czy jest królem. Ludzie nie zrozumieli tej misji, ani Chrystusowej odpowiedzi. Poprzez ukoronowanie cierniową koroną zakpili sobie z królewskiej godności Chrystusa. Ale to jednak nie zmienia faktu. Odrzucony przez ludzi Król pozostaje nim nadal, bo to On przynosi zbuntowanej ludzkości zbawienie i pokój. Przynosi prawdę i nadzieję wiecznego życia.'),
(14, 'Bolesna', 'Dźwiganie Krzyża na Kalwarię', '"Jeśli kto chce iść za mną, niech weźmie swój krzyż i niech mnie naśladuje" (Mk 8,34). Te słowa Chrystusa stanowią gorące zaproszenie każdego człowieka, by krzyż swej codzienności związał z Chrystusem, z krzyżem swojego Zbawiciela. Wtedy wszystko nabiera nowego sensu i nowego znaczenia. Idę więc ze swoim krzyżem, a obok mnie idzie mój brat i moja siostra, mój bliźni i też niesie swój krzyż. Czy potrafię znaleźć się w roli Szymona z Cyreny czy Weroniki, by choć odrobinę ulgi i pomocy dać mojemu bliźniemu?'),
(15, 'Bolesna', 'Ukrzyżowanie i śmierć Chrystusa', '"Gdy przyszli na miejsce zwane Golgotą, ukrzyżowali tam Jezusa" (Łk 23,33). Zanim jednak nastąpił prawdziwy kres dramatu i wypowiedziane zostały przez Chrystusa ostatnie słowa: "Wykonało się", na Wzgórzu Kalwarii działo się jeszcze bardzo wiele ważnych spraw. "Ojcze przebacz im, bo nie wiedzą, co czynią" - uczył nas z Krzyża Chrystus. Do skruszonego i żałującego za swe winy współtowarzysza umierania powiedział: "Dziś będziesz ze mną w raju". Na koniec zostawił nam testament: "Niewiasto oto syn Twój" "Oto Matka twoja" i powierzył macierzyńskiej opiece Maryi całą ludzkość i każdego z nas. Panie Jezu, niech wydarzenia z Kalwarii nauczą i mnie przebaczenia oraz miłości do Twojej i mojej Matki.'),

-- CHWALEBNE
(16, 'Chwalebna', 'Zmartwychwstanie Jezusa Chrystusa', '"Wtedy oświecił ich umysły, aby zrozumieli Pisma i rzekł do Nich: Tak jest napisane. Mesjasz będzie cierpiał i trzeciego dnia zmartwychwstanie, w imię Jego głoszone będzie nawrócenie i odpuszczenie grzechów wszystkim narodom" (Łk 24,45). Wydarzenia zapowiadane przez Pisma, a realizowane w życiu i przez życie Jezusa z Nazaretu, zmieniły bieg historii, a ludzkości dały nadzieję życia wiecznego. Każdy człowiek został zaproszony do uczestnictwa w Zmartwychwstaniu Chrystusa. Współuczestniczyć w Zmartwychwstaniu Chrystusa może ten, kto Go w życiu naśladuje w dźwiganiu krzyża i razem z Nim umiera. Umocnij, Panie, moje kroki na Twoich ścieżkach, abym nigdy z nich nie zszedł, ale wiernie trwał przy Tobie.'),
(17, 'Chwalebna', 'Wniebowstąpienie Chrystusa', '"W domu Ojca mego jest mieszkań wiele. Idę przygotować wam mieszkanie" (J 14,2). Tak zapowiedział Chrystus swoje Wniebowstąpienie i jego znaczenie dla każdego z nas. Miejsce w domu Ojca jest przydzielone tym, którzy uwierzyli i rozpoznali Chrystusa w głodnym, bezdomnym, cierpiącym i udzielili Mu pomocy. Ci usłyszą: "Pójdźcie, błogosławieni Ojca mego, weźcie w posiadanie Królestwo przygotowane wam od założenia świata". Panie mój i Mistrzu, naucz mnie widzieć i słyszeć Twój głos prośby o moją pomoc wypowiadanej ludzkim głosem i poprzez ludzkie biedy.'),
(18, 'Chwalebna', 'Zesłanie Ducha Świętego', '"I wszyscy zostali napełnieni Duchem Świętym" (Dz 2,4). Przestraszona wydarzeniami związanymi z męką i śmiercią Chrystusa wspólnota apostołów spotykała się w ukryciu na modlitwie razem z Maryją, Matką Jezusa. Wydarzyło się coś szczególnego, co przemieniło ich serca i zmieniło ich życiowe postawy. Zaczęli odważnie głosić, że Jezus żyje, bo prawdziwie zmartwychwstał i że tylko On, Jezus jest Panem i nadzieją każdego człowieka. A wszystko to stało się dzięki darom, które otrzymali Apostołowie w dniu zesłania Ducha św. Panie ześlij Ducha św. i na nas, abyśmy umieli spełnić Twoje polecenie dzisiaj: "Będziecie mi świadkami aż po krańce świata".'),
(19, 'Chwalebna', 'Wniebowzięcie NMP', '"Ojcze, chcę, aby także ci, których mi dałeś, byli ze mną, gdzie Ja jestem" (J 17,24). Konsekwentnie do słów wcześniej wypowiedzianych postąpił Chrystus wobec Maryi, swojej Matki, która przecież została mu dana. Była z Nim we wszystkich sprawach: w Betlejem, gdzie się rodził, w Nazarecie, gdzie wzrastał w łasce u Boga i ludzi, na Kalwarii, gdzie realizował najważniejszy etap swej misji - zbawienie świata. Przez Niepokalane Poczęcie Maryja wolna od jakiegokolwiek grzechu, uwolniona została także od długiego oczekiwania w grobie na dzień zmartwychwstania. Jej zaśnięcie, była zarazem przejściem do zmartwychwstania i pełnym wejściem do chwały z duszą i ciałem. Wielkie rzeczy uczynił Ci, Maryjo, Wszechmocny, bo byłaś Mu wierna i całkowicie oddana.'),
(20, 'Chwalebna', 'Ukoronowanie Maryi w niebie', '"Zwycięzcy dam zasiąść ze Mną na Moim tronie" (Ap 3,21). Maryja odniosła zwycięstwo. Pokonała grzech i śmierć a także ludzką słabość. W Liście św. Pawła (2 Tm 2,11) czytamy: "Jeżeliśmy bowiem z Nim współumarli, wespół też z Nim żyć będziemy. Jeśli trwamy w cierpliwości, wespół z Nim też królować będziemy". Królowanie Maryi oznacza świadczenie miłości i opieki tym, dla których stała się Matką, oraz troska o to, by nikt z odkupionych przez Jej syna nie zginął, ale doszedł do pełni życia wiecznego. Maryjo, nasza Matko i Królowo, prowadź nas bezpiecznie do Swego Syna.');

-- Aktualizacja linków do obrazków
DO $$
DECLARE
    base_url text := 'https://jjlxuqnwbakmiwqfycha.supabase.co/storage/v1/object/public/mysteries/';
BEGIN

    -- RADOSNE
    UPDATE public.mysteries SET image_url = base_url || 'radosna_zwiastowanie.jpg' WHERE id = 1;
    UPDATE public.mysteries SET image_url = base_url || 'radosna_nawiedzenie.jpg' WHERE id = 2;
    UPDATE public.mysteries SET image_url = base_url || 'radosna_narodzenie.jpg' WHERE id = 3;
    UPDATE public.mysteries SET image_url = base_url || 'radosna_ofiarowanie.jpg' WHERE id = 4;
    UPDATE public.mysteries SET image_url = base_url || 'radosna_odnalezienie.jpg' WHERE id = 5;

    -- ŚWIATŁA
    UPDATE public.mysteries SET image_url = base_url || 'swiatla_chrzest.jpg' WHERE id = 6;
    UPDATE public.mysteries SET image_url = base_url || 'swiatla_kana.jpg' WHERE id = 7;
    UPDATE public.mysteries SET image_url = base_url || 'swiatla_gloszenie.jpg' WHERE id = 8;
    UPDATE public.mysteries SET image_url = base_url || 'swiatla_przemienienie.jpg' WHERE id = 9;
    UPDATE public.mysteries SET image_url = base_url || 'swiatla_eucharystia.jpg' WHERE id = 10;

    -- BOLESNE
    UPDATE public.mysteries SET image_url = base_url || 'bolesna_ogrojec.jpg' WHERE id = 11;
    UPDATE public.mysteries SET image_url = base_url || 'bolesna_biczowanie.jpg' WHERE id = 12;
    UPDATE public.mysteries SET image_url = base_url || 'bolesna_ukoronowanie.jpg' WHERE id = 13;
    UPDATE public.mysteries SET image_url = base_url || 'bolesna_krzyz.jpg' WHERE id = 14;
    UPDATE public.mysteries SET image_url = base_url || 'bolesna_ukrzyzowanie.jpg' WHERE id = 15;

    -- CHWALEBNE
    UPDATE public.mysteries SET image_url = base_url || 'chwalebna_zmartwychwstanie.jpg' WHERE id = 16;
    UPDATE public.mysteries SET image_url = base_url || 'chwalebna_wniebowstapienie.jpg' WHERE id = 17;
    UPDATE public.mysteries SET image_url = base_url || 'chwalebna_zeslanie.jpg' WHERE id = 18;
    UPDATE public.mysteries SET image_url = base_url || 'chwalebna_wniebowziecie.jpg' WHERE id = 19;
    UPDATE public.mysteries SET image_url = base_url || 'chwalebna_ukoronowanie.jpg' WHERE id = 20;

END $$;
