drop extension if exists "pg_net";


  create table "public"."acknowledgments" (
    "id" bigint generated by default as identity not null,
    "user_id" uuid not null,
    "mystery_id" integer not null,
    "created_at" timestamp with time zone not null default timezone('utc'::text, now())
      );


alter table "public"."acknowledgments" enable row level security;


  create table "public"."groups" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "created_at" timestamp with time zone not null default timezone('utc'::text, now())
      );


alter table "public"."groups" enable row level security;


  create table "public"."intentions" (
    "id" bigint generated by default as identity not null,
    "month" integer not null,
    "year" integer not null,
    "content" text not null,
    "created_at" timestamp with time zone not null default timezone('utc'::text, now()),
    "title" text
      );


alter table "public"."intentions" enable row level security;


  create table "public"."mysteries" (
    "id" integer not null,
    "part" text not null,
    "name" text not null,
    "meditation" text,
    "image_url" text
      );


alter table "public"."mysteries" enable row level security;


  create table "public"."profiles" (
    "id" uuid not null,
    "full_name" text,
    "role" text default 'user'::text,
    "group_id" bigint,
    "created_at" timestamp with time zone not null default timezone('utc'::text, now()),
    "email" text,
    "rose_pos" integer
      );


alter table "public"."profiles" enable row level security;

CREATE UNIQUE INDEX acknowledgments_pkey ON public.acknowledgments USING btree (id);

CREATE UNIQUE INDEX acknowledgments_user_id_mystery_id_key ON public.acknowledgments USING btree (user_id, mystery_id);

CREATE UNIQUE INDEX groups_pkey ON public.groups USING btree (id);

CREATE UNIQUE INDEX intentions_month_year_key ON public.intentions USING btree (month, year);

CREATE UNIQUE INDEX intentions_pkey ON public.intentions USING btree (id);

CREATE UNIQUE INDEX mysteries_pkey ON public.mysteries USING btree (id);

CREATE UNIQUE INDEX profiles_pkey ON public.profiles USING btree (id);

alter table "public"."acknowledgments" add constraint "acknowledgments_pkey" PRIMARY KEY using index "acknowledgments_pkey";

alter table "public"."groups" add constraint "groups_pkey" PRIMARY KEY using index "groups_pkey";

alter table "public"."intentions" add constraint "intentions_pkey" PRIMARY KEY using index "intentions_pkey";

alter table "public"."mysteries" add constraint "mysteries_pkey" PRIMARY KEY using index "mysteries_pkey";

alter table "public"."profiles" add constraint "profiles_pkey" PRIMARY KEY using index "profiles_pkey";

alter table "public"."acknowledgments" add constraint "acknowledgments_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.profiles(id) ON DELETE CASCADE not valid;

alter table "public"."acknowledgments" validate constraint "acknowledgments_user_id_fkey";

alter table "public"."acknowledgments" add constraint "acknowledgments_user_id_mystery_id_key" UNIQUE using index "acknowledgments_user_id_mystery_id_key";

alter table "public"."intentions" add constraint "intentions_month_check" CHECK (((month >= 1) AND (month <= 12))) not valid;

alter table "public"."intentions" validate constraint "intentions_month_check";

alter table "public"."intentions" add constraint "intentions_month_year_key" UNIQUE using index "intentions_month_year_key";

alter table "public"."profiles" add constraint "profiles_group_id_fkey" FOREIGN KEY (group_id) REFERENCES public.groups(id) ON DELETE SET NULL not valid;

alter table "public"."profiles" validate constraint "profiles_group_id_fkey";

alter table "public"."profiles" add constraint "profiles_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."profiles" validate constraint "profiles_id_fkey";

alter table "public"."profiles" add constraint "profiles_role_check" CHECK ((role = ANY (ARRAY['admin'::text, 'user'::text]))) not valid;

alter table "public"."profiles" validate constraint "profiles_role_check";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.get_my_group_id()
 RETURNS bigint
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT group_id FROM profiles WHERE id = auth.uid();
$function$
;

CREATE OR REPLACE FUNCTION public.get_mystery_id_for_user(p_user_id uuid)
 RETURNS integer
 LANGUAGE plpgsql
AS $function$
DECLARE
    start_date date := '2024-01-01'; -- Data startu rotacji
    months_passed integer;
    user_pos integer;
    calculated_id integer;
BEGIN
    -- Pobierz pozycję użytkownika
    SELECT rose_pos INTO user_pos FROM public.profiles WHERE id = p_user_id;

    -- Jeśli user nie ma przypisanej pozycji (np. Admin bez grupy), zwróć NULL
    IF user_pos IS NULL THEN
        RETURN NULL;
    END IF;

    -- Oblicz ile miesięcy minęło
    SELECT EXTRACT(YEAR FROM age(now(), start_date)) * 12 +
           EXTRACT(MONTH FROM age(now(), start_date)) INTO months_passed;

    -- Algorytm Żywego Różańca:
    -- (Pozycja startowa + przesunięcie miesięczne) modulo 20
    calculated_id := ((user_pos - 1 + months_passed) % 20) + 1;

    RETURN calculated_id;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.is_admin()
 RETURNS boolean
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT EXISTS (
    SELECT 1 FROM profiles
    WHERE id = auth.uid()
    AND role = 'admin'
  );
$function$
;

CREATE OR REPLACE FUNCTION public.move_user_to_group(p_user_id uuid, p_group_id bigint)
 RETURNS integer
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
    free_pos integer;
BEGIN
    -- SCENARIUSZ 1: Wyrzucamy z grupy (ustawiamy brak)
    IF p_group_id IS NULL THEN
        UPDATE public.profiles
        SET group_id = NULL, rose_pos = NULL
        WHERE id = p_user_id;
        
        -- Czyścimy potwierdzenia
        DELETE FROM public.acknowledgments WHERE user_id = p_user_id;
        
        RETURN 0;
    END IF;

    -- SCENARIUSZ 2: Przenosimy do nowej grupy
    -- Szukamy pierwszego wolnego miejsca (1-20)
    SELECT s.i
    FROM generate_series(1, 20) AS s(i)
    WHERE NOT EXISTS (
        SELECT 1 FROM public.profiles
        WHERE group_id = p_group_id AND rose_pos = s.i
    )
    ORDER BY s.i
    LIMIT 1
    INTO free_pos;

    -- Jeśli nie ma miejsca
    IF free_pos IS NULL THEN
        RAISE EXCEPTION 'Ta róża jest pełna (20 osób)! Nie można przenieść.';
    END IF;

    -- Aktualizujemy profil
    UPDATE public.profiles
    SET group_id = p_group_id,
        rose_pos = free_pos
    WHERE id = p_user_id;

    -- Czyścimy stare potwierdzenia (bo nowa tajemnica to nowe wyzwanie)
    DELETE FROM public.acknowledgments WHERE user_id = p_user_id;

    RETURN free_pos;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.rotate_group_members(p_group_id bigint)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
begin
  -- 1. Czyścimy potwierdzenia dla tej grupy (bo dostają nowe tajemnice)
  delete from public.acknowledgments
  where user_id in (
    select id from public.profiles where group_id = p_group_id
  );

  -- 2. Rotacja pozycji: 1->2, 2->3 ... 20->1
  -- Używamy tymczasowej logiki, aby uniknąć konfliktów unikalności (jeśli są)
  update public.profiles
  set rose_pos = case
      when rose_pos >= 20 then 1
      else rose_pos + 1
  end
  where group_id = p_group_id;
end;
$function$
;

grant delete on table "public"."acknowledgments" to "anon";

grant insert on table "public"."acknowledgments" to "anon";

grant references on table "public"."acknowledgments" to "anon";

grant select on table "public"."acknowledgments" to "anon";

grant trigger on table "public"."acknowledgments" to "anon";

grant truncate on table "public"."acknowledgments" to "anon";

grant update on table "public"."acknowledgments" to "anon";

grant delete on table "public"."acknowledgments" to "authenticated";

grant insert on table "public"."acknowledgments" to "authenticated";

grant references on table "public"."acknowledgments" to "authenticated";

grant select on table "public"."acknowledgments" to "authenticated";

grant trigger on table "public"."acknowledgments" to "authenticated";

grant truncate on table "public"."acknowledgments" to "authenticated";

grant update on table "public"."acknowledgments" to "authenticated";

grant delete on table "public"."acknowledgments" to "service_role";

grant insert on table "public"."acknowledgments" to "service_role";

grant references on table "public"."acknowledgments" to "service_role";

grant select on table "public"."acknowledgments" to "service_role";

grant trigger on table "public"."acknowledgments" to "service_role";

grant truncate on table "public"."acknowledgments" to "service_role";

grant update on table "public"."acknowledgments" to "service_role";

grant delete on table "public"."groups" to "anon";

grant insert on table "public"."groups" to "anon";

grant references on table "public"."groups" to "anon";

grant select on table "public"."groups" to "anon";

grant trigger on table "public"."groups" to "anon";

grant truncate on table "public"."groups" to "anon";

grant update on table "public"."groups" to "anon";

grant delete on table "public"."groups" to "authenticated";

grant insert on table "public"."groups" to "authenticated";

grant references on table "public"."groups" to "authenticated";

grant select on table "public"."groups" to "authenticated";

grant trigger on table "public"."groups" to "authenticated";

grant truncate on table "public"."groups" to "authenticated";

grant update on table "public"."groups" to "authenticated";

grant delete on table "public"."groups" to "service_role";

grant insert on table "public"."groups" to "service_role";

grant references on table "public"."groups" to "service_role";

grant select on table "public"."groups" to "service_role";

grant trigger on table "public"."groups" to "service_role";

grant truncate on table "public"."groups" to "service_role";

grant update on table "public"."groups" to "service_role";

grant delete on table "public"."intentions" to "anon";

grant insert on table "public"."intentions" to "anon";

grant references on table "public"."intentions" to "anon";

grant select on table "public"."intentions" to "anon";

grant trigger on table "public"."intentions" to "anon";

grant truncate on table "public"."intentions" to "anon";

grant update on table "public"."intentions" to "anon";

grant delete on table "public"."intentions" to "authenticated";

grant insert on table "public"."intentions" to "authenticated";

grant references on table "public"."intentions" to "authenticated";

grant select on table "public"."intentions" to "authenticated";

grant trigger on table "public"."intentions" to "authenticated";

grant truncate on table "public"."intentions" to "authenticated";

grant update on table "public"."intentions" to "authenticated";

grant delete on table "public"."intentions" to "service_role";

grant insert on table "public"."intentions" to "service_role";

grant references on table "public"."intentions" to "service_role";

grant select on table "public"."intentions" to "service_role";

grant trigger on table "public"."intentions" to "service_role";

grant truncate on table "public"."intentions" to "service_role";

grant update on table "public"."intentions" to "service_role";

grant delete on table "public"."mysteries" to "anon";

grant insert on table "public"."mysteries" to "anon";

grant references on table "public"."mysteries" to "anon";

grant select on table "public"."mysteries" to "anon";

grant trigger on table "public"."mysteries" to "anon";

grant truncate on table "public"."mysteries" to "anon";

grant update on table "public"."mysteries" to "anon";

grant delete on table "public"."mysteries" to "authenticated";

grant insert on table "public"."mysteries" to "authenticated";

grant references on table "public"."mysteries" to "authenticated";

grant select on table "public"."mysteries" to "authenticated";

grant trigger on table "public"."mysteries" to "authenticated";

grant truncate on table "public"."mysteries" to "authenticated";

grant update on table "public"."mysteries" to "authenticated";

grant delete on table "public"."mysteries" to "service_role";

grant insert on table "public"."mysteries" to "service_role";

grant references on table "public"."mysteries" to "service_role";

grant select on table "public"."mysteries" to "service_role";

grant trigger on table "public"."mysteries" to "service_role";

grant truncate on table "public"."mysteries" to "service_role";

grant update on table "public"."mysteries" to "service_role";

grant delete on table "public"."profiles" to "anon";

grant insert on table "public"."profiles" to "anon";

grant references on table "public"."profiles" to "anon";

grant select on table "public"."profiles" to "anon";

grant trigger on table "public"."profiles" to "anon";

grant truncate on table "public"."profiles" to "anon";

grant update on table "public"."profiles" to "anon";

grant delete on table "public"."profiles" to "authenticated";

grant insert on table "public"."profiles" to "authenticated";

grant references on table "public"."profiles" to "authenticated";

grant select on table "public"."profiles" to "authenticated";

grant trigger on table "public"."profiles" to "authenticated";

grant truncate on table "public"."profiles" to "authenticated";

grant update on table "public"."profiles" to "authenticated";

grant delete on table "public"."profiles" to "service_role";

grant insert on table "public"."profiles" to "service_role";

grant references on table "public"."profiles" to "service_role";

grant select on table "public"."profiles" to "service_role";

grant trigger on table "public"."profiles" to "service_role";

grant truncate on table "public"."profiles" to "service_role";

grant update on table "public"."profiles" to "service_role";


  create policy "Insert Policy"
  on "public"."acknowledgments"
  as permissive
  for insert
  to public
with check ((auth.uid() = user_id));



  create policy "Users can delete own"
  on "public"."acknowledgments"
  as permissive
  for delete
  to public
using ((auth.uid() = user_id));



  create policy "Users can insert own"
  on "public"."acknowledgments"
  as permissive
  for insert
  to public
with check ((auth.uid() = user_id));



  create policy "Users see own, Admin sees all"
  on "public"."acknowledgments"
  as permissive
  for select
  to public
using (((auth.uid() = user_id) OR public.is_admin()));



  create policy "Admin full access to groups"
  on "public"."groups"
  as permissive
  for all
  to public
using (public.is_admin())
with check (public.is_admin());



  create policy "Każdy widzi grupy"
  on "public"."groups"
  as permissive
  for select
  to public
using (true);



  create policy "Read access for authenticated"
  on "public"."groups"
  as permissive
  for select
  to public
using ((auth.role() = 'authenticated'::text));



  create policy "Admin can manage intentions"
  on "public"."intentions"
  as permissive
  for all
  to public
using (public.is_admin())
with check (public.is_admin());



  create policy "Anyone can read intentions"
  on "public"."intentions"
  as permissive
  for select
  to public
using (true);



  create policy "Enable all access for authenticated users"
  on "public"."intentions"
  as permissive
  for all
  to authenticated
using (true)
with check (true);



  create policy "Enable read access for all users"
  on "public"."intentions"
  as permissive
  for select
  to public
using (true);



  create policy "Każdy widzi tajemnice"
  on "public"."mysteries"
  as permissive
  for select
  to public
using (true);



  create policy "Allow Read All"
  on "public"."profiles"
  as permissive
  for select
  to public
using ((auth.role() = 'authenticated'::text));



  create policy "Allow Service Role Full Access"
  on "public"."profiles"
  as permissive
  for all
  to service_role
using (true)
with check (true);



  create policy "Allow Update Own"
  on "public"."profiles"
  as permissive
  for update
  to public
using ((auth.uid() = id));



  create policy "Enable all access for service role"
  on "public"."profiles"
  as permissive
  for all
  to service_role
using (true)
with check (true);



  create policy "Każdy widzi profile"
  on "public"."profiles"
  as permissive
  for select
  to public
using (true);



  create policy "Profile Update"
  on "public"."profiles"
  as permissive
  for update
  to public
using (((auth.uid() = id) OR public.is_admin()));



  create policy "User edytuje siebie"
  on "public"."profiles"
  as permissive
  for update
  to public
using ((auth.uid() = id));



